### ISSUE TITLE
Runtime error when datastore can't be opened

### ISSUE THREAD

**Issue by rexxars** [sanity-io/gradient#108]
I assume this should exit more gracefully than this?

```
espenh@plumm ~/webdev/gradient $ ~/go/src/github.com/sanity-io/gradient/gradientctl -c ./config/gradient.yml security signtoken --grant "**=read,create,update,manage" god
09:56:12.604 ERROR system Failed to start, will shut down: Could not open data store "default": dial tcp: lookup postgres on 127.0.1.1:53: no such host
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4e536f]

goroutine 1 [running]:
panic(0xb87440, 0xc820010150)
    /usr/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/sanity-io/gradient/system.(*Manager).Close(0x0, 0x0, 0x0)
    /home/espenh/go/src/github.com/sanity-io/gradient/system/manager.go:153 +0x3af
github.com/sanity-io/gradient/system.NewManagerFromConfig.func1(0xc8201394fe, 0xc820139810, 0xc820139808)
    /home/espenh/go/src/github.com/sanity-io/gradient/system/manager.go:84 +0xf8
github.com/sanity-io/gradient/system.NewManagerFromConfig(0xc8200f7540, 0x1, 0x1, 0xc8201230b0, 0x1, 0x1, 0xc8200f7660, 0xc8200f7680, 0xc820032408, 0x0, ...)
    /home/espenh/go/src/github.com/sanity-io/gradient/system/manager.go:95 +0x666
github.com/sanity-io/gradient/cmd/gradientctl/common.(*GlobalOptions).GetManagerWithFlags(0x10e0c40, 0x0, 0x441a6e, 0x0, 0x0)
    /home/espenh/go/src/github.com/sanity-io/gradient/cmd/gradientctl/common/options.go:325 +0x122
github.com/sanity-io/gradient/cmd/gradientctl/common.(*GlobalOptions).GetManager(0x10e0c40, 0xc8200f6d00)
    /home/espenh/go/src/github.com/sanity-io/gradient/cmd/gradientctl/common/options.go:307 +0x35
github.com/sanity-io/gradient/cmd/gradientctl/security.cmdSignToken.Execute(0x0, 0xc8200ebb90, 0x1, 0x1, 0x10e0c40, 0xc820121e30, 0x1, 0x7, 0x0, 0x0)
    /home/espenh/go/src/github.com/sanity-io/gradient/cmd/gradientctl/security/sign.go:73 +0x786
github.com/sanity-io/gradient/cmd/gradientctl/security.(*cmdSignToken).Execute(0xc820122570, 0xc820121e30, 0x1, 0x7, 0x0, 0x0)
    <autogenerated>:3 +0xc5
github.com/sanity-io/gradient/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc820018ff0, 0xc82000a110, 0x7, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/espenh/go/src/github.com/sanity-io/gradient/vendor/github.com/jessevdk/go-flags/parser.go:301 +0xa10
github.com/sanity-io/gradient/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc820018ff0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/espenh/go/src/github.com/sanity-io/gradient/vendor/github.com/jessevdk/go-flags/parser.go:175 +0x9b
main.main()
    /home/espenh/go/src/github.com/sanity-io/gradient/cmd/gradientctl/main.go:37 +0x116
```

**Comment by erikgrinaker** [comment]
This is fixed on `master`:

```
$ ./build/gradientadm -c gradient.yml sign-token --grant "**=read,create,update,manage" god
Could not open data store "default": Could not create connection pool: dial tcp: lookup postgres: no such host
```
