### ISSUE TITLE
Delete attempt of referee document gives internal error and 500

### ISSUE THREAD

**Issue by thomax** [sanity-io/gradient#284]
I would expect a code 400 and "Sorry, that document is referenced from [this other guy]. Get rid of all references and try again."

```
delete failed { Error: The mutation(s) failed: Document "hioa/track_case-studies" cannot be deleted as there are references to it from "hioa/progress_article_48b549cdeb91e633f693e994deb50907-track_case-studies"
    at extractError (/Users/thomas/code/vega/vega-importer/node_modules/@sanity/client/src/http/request.js:112:19)
    at Request._callback (/Users/thomas/code/vega/vega-importer/node_modules/@sanity/client/src/http/request.js:64:23)
    at Request.self.callback (/Users/thomas/code/vega/vega-importer/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/thomas/code/vega/vega-importer/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/thomas/code/vega/vega-importer/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:286:16)
  details:
   { description: 'The mutation(s) failed: Document "hioa/track_case-studies" cannot be deleted as there are references to it from "hioa/progress_article_48b549cdeb91e633f693e994deb50907-track_case-studies"',
     items: [ [Object] ],
     type: 'mutationError' },
  responseBody: '{\n  "error": {\n    "description": "The mutation(s) failed: Document \\"hioa/track_case-studies\\" cannot be deleted as there are references to it from \\"hioa/progress_article_48b549cdeb91e633f693e994deb50907-track_case-studies\\"",\n    "items": [\n      {\n        "error": {\n          "description": "Internal server error",\n          "type": "internalError"\n        },\n        "index": 0\n      }\n    ],\n    "type": "mutationError"\n  }\n}',
  statusCode: 500 }
```

**Comment by erikgrinaker** [comment]
This seems to have been fixed on `master`, deleting a referenced document yields a `409 Conflict` with:

```json
{"error":{"description":"The mutation(s) failed: Document \"target\" cannot be deleted as there are references to it from \"source\"","items":[{"error":{"description":"Document \"target\" cannot be deleted as there are references to it from \"source\"","id":"target","referencingIDs":["source"],"type":"documentHasExistingReferencesError"},"index":0}],"type":"mutationError"}}
```
